### ISSUE TITLE
요약에 대한 요청-응답 

### ISSUE THREAD

**Issue by YoungwooKim09** [SummaryWagon/SummaryWagon#20]
### 😎 작업 내용
- [x] 백엔드 서버에서 요약 작업 실행
- [x] 해당 작업에 대한 소요 시간 측정

### 🔥 우선순위
- [ ] 높음
- [x] 중간
- [ ] 낮음

### 🎣 작업 상태
- [ ] 진행 중
- [ ] 보류 중
- [x] 완료

### 🗓️ 작업 기한
- [x] 2023-05-06

### 🧑🏻‍💻 작업 참여자
- [x] @YoungwooKim09

**Comment by jamiehun** [comment]
lambda와 openai api 간의 속도 차이 비교
